import "./globals.css";
import { poppins,spaceGrotesk ,bricolageGrotesque} from "./font";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "New Matha Sweets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    className={`${spaceGrotesk.variable} ${poppins.variable} ${bricolageGrotesque.variable}`}
    
    >
      <Navbar/>
      <body
        className={`${bricolageGrotesque.className}`}
      >
        {children}
      </body>
    </html>
  );
}
