import { Geist, Geist_Mono,Poppins,Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight:['300','400','500','600','700','800'],
  subsets: ["latin"],
});
const space_Grotesk = Space_Grotesk({
  variable: "--font-space_grotesk",
  weight:['300','400','500','600','700','800'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Abiskar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
